### ISSUE TITLE
Stop using Destructurama.FSharp's .NetCore variant package

### ISSUE THREAD

**Issue by bartelink** [jet/dotnet-templates#36]
Per @baronfel (maintainer of `Destructurama.FSharp`) on the F# slack, this shim package is completely unnecessary, being a long-gone short term hack; the official (non `.NetCore`-suffixed) package has long been multitargeted

**Comment by baronfel** [comment]
The tracking issue to make a stable version of the 'official' Destructurama.FSharp package is https://github.com/destructurama/fsharp/issues/11

**Comment by bartelink** [comment]
There's now a `1.1.1-dev-00033` which includes relaxed FSharp.Core dependencies based on https://github.com/destructurama/fsharp/pull/13

**Comment by bartelink** [comment]
Resolved in https://github.com/jet/dotnet-templates/commit/457f642f321c44ed194ca7a3f03ac30b8d37dfaf
