### ISSUE TITLE
Fix equinox-web-csharp template guids

### ISSUE THREAD

**Issue by bartelink** [jet/dotnet-templates#8]
As noted by @aarondandy, the C# template's sln marks the projects as being F#. This is highly likely to be due to me copy-pasting the sln file. This should be addressed in order to ensure no nasty side-effects like tooling or intellisense not working happens.

**Comment by bartelink** [comment]
Also wondering if a ready-to-run project like this needs to have the project guids be replaced or not (I'm thinking that it should not matter given one'd never instantiate the template twice within an actual sln?)

**Comment by aarondandy** [comment]
Having two web services for a single domain would be a bit odd IMO but, to each their own! I think some people may have multiple domains under one mega solution if they are doing a huge mono-repo though or building a distributed monolith.

**Comment by bartelink** [comment]
The project type guids should be fixed in [`1.2.0`](https://github.com/jet/dotnet-templates/releases/tag/1.2.0).

They were taken from the guids inserted by doing an aspnet web api project and a classlib.

Closing for now - feel free to reopen if anything seems wrong.
