### ISSUE TITLE
Upgrade to dotnet 2.2

### ISSUE THREAD

**Issue by aarondandy** [jet/dotnet-templates#9]
I'm not really sure if this is even much of a problem but I noticed that the generated web app when using eqxwebcs will reference the newer 2.2 version of `Microsoft.AspNetCore.App` but the project targets `netcoreapp2.1`. I'm unsure if this is a bug or feature, thoughts?

See: https://github.com/jet/dotnet-templates/blob/73b380b270c7794714aee0bf36e61204eaa22a0d/equinox-web-csharp/Web/Web.csproj#L4

**Comment by bartelink** [comment]
Very eagle eyed of you ;)

In general for the template, the aim is to have as few expectations as possible e.g.
- C# 7.1 unless someone finds a compelling use of a later feature which cleans things up in a compelling way
- LTS supported netcore
until there's a compelling reason to take a higher dependency.

In the Equinox repo, from which the F# version is derived, and the C# one was hand-cloned, the repo [pins the SDK version to `2.1.402`](https://github.com/jet/equinox/blob/master/global.json).

I suspect doing that in this repo is probably a good idea for predictable experience.

I'm not sure what the recommended approach is wrt all this in a dotnet template - i.e. I'm not sure how keeping web templates in step with aspnetcore is supposed to work. (Cant fish out a link for the fact that VS still needs these templates to be wrapped in a VS gallery installer thing when third party IDEs can consume them from the registered `dotnet new` list no problem; hopefully there will be clear guidance and/or a proper story for this before VS 2019 ships in full)

**Comment by bartelink** [comment]
I'm thinking to close as a wontfix, as I personally don't have space for it, and it seems relatively low priority - what say you @aarondandy ?

**Comment by bartelink** [comment]
We'll likely move stuff to `netcoreapp3.1` as the `v3` branches for Equinox and Propulsion (which do same) become master

**Comment by bartelink** [comment]
Resolved by #48. General intention is to have templates target LTS versions, but as these these templates are not tied closely to the framework as a whole, there's no major impetus to require anything more stringent than that as far as I can determine.
